version: "3.7"

services:
  csgo:
    image: kmallea/csgo:latest
    container_name: csgo-ds
    environment:
      SERVER_HOSTNAME: "PUV-CSGO"
      SERVER_PASSWORD: ${CSGO_SERVER_PASSWORD}
      RCON_PASSWORD: ${CSGO_RCON_PASSWORD}
      STEAM_ACCOUNT: ${CSGO_STEAM_ACCOUNT}
      AUTHKEY: ${CSGO_AUTH_KEY}
      SOURCEMOD_ADMINS: comma,delimited,list,of,steam,ids
      IP: 0.0.0.0
      PORT: 27015
      TV_PORT: 27020
      TICKRATE: 128
      FPS_MAX: 300
      GAME_TYPE: 0
      GAME_MODE: 1
      MAP: de_dust2
      MAPGROUP: mg_active
      MAXPLAYERS: 12
      TV_ENABLE: 1
      LAN: 0
      RETAKES: 0
    volumes:
      - csgo-data
    network_mode: "host"
    restart: unless-stopped
    stdin_open: true
    tty: true

volumes:
  csgo-data:
    name: csgo-data
